services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    networks:
      - odoo-net

  odoo-web:
    image: odoo:18.0
    container_name: odoo-web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo18:/mnt/odoo
      - ./modules/operator:/mnt/extra-addons/operator
      - ./entrypoint.sh:/docker-entrypoint-init.d/entrypoint.sh
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ["/docker-entrypoint-init.d/entrypoint.sh"]
    networks:
      - odoo-net

volumes:
  odoo-db-data:

networks:
  odoo-net:
